reference: /path/to/reference.fasta
k-size: 7
threshold: 40.0

reads:
  sample_1:
   /path/to/query.fastq
  # sample_2: 
  # Additional samples follow the same format
 


out_dir: /path/to/output

deanalysis : "no"

factors: [Group] #list of names of the factors/co-variates.
sample_info: #
  sample_1 : [control] #list of names of level of the factors, which the sample corresponds to.
  sample_2 : [control]
  sample_3 : [control]
  sample_4 : [treated]
  sample_5 : [treated]
  sample_6 : [treated]
design: Group
